// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';
import {main} from '../models';

export function AddToWorkspace():Promise<json.RawMessage>;

export function CLIFound():Promise<boolean>;

export function CheckForUpdates():Promise<json.RawMessage>;

export function CloseWorkspace():Promise<void>;

export function DiffFile(arg1:string):Promise<json.RawMessage>;

export function GetConfig(arg1:string):Promise<json.RawMessage>;

export function GetState():Promise<json.RawMessage>;

export function InitWorkspace(arg1:string):Promise<void>;

export function InstallCLI():Promise<void>;

export function InstallFile(arg1:string):Promise<json.RawMessage>;

export function ListBranches():Promise<json.RawMessage>;

export function ListManifests():Promise<json.RawMessage>;

export function ListWorkspaces():Promise<Array<main.WorkspaceInfo>>;

export function OpenFile(arg1:string):Promise<void>;

export function ReadTelemetryLog():Promise<json.RawMessage>;

export function RemoveFromWorkspace():Promise<json.RawMessage>;

export function RestartDaemon():Promise<void>;

export function RunTelemetry():Promise<json.RawMessage>;

export function SelectWorkspace():Promise<Record<string, any>>;

export function SetConfig(arg1:json.RawMessage):Promise<json.RawMessage>;

export function SetOverride(arg1:string,arg2:string):Promise<json.RawMessage>;

export function SetWorkspaceMenuVisible(arg1:boolean):Promise<void>;

export function SkipUpdate(arg1:string):Promise<json.RawMessage>;

export function SyncManifests():Promise<json.RawMessage>;

export function UninstallFile(arg1:string):Promise<json.RawMessage>;

export function UpdateAll():Promise<json.RawMessage>;

export function UpdateCLI():Promise<json.RawMessage>;

export function Version():Promise<string>;
