// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiffFile(arg1) {
  return window['go']['main']['App']['DiffFile'](arg1);
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function InitWorkspace(arg1) {
  return window['go']['main']['App']['InitWorkspace'](arg1);
}

export function InstallFile(arg1) {
  return window['go']['main']['App']['InstallFile'](arg1);
}

export function ListBranches(arg1) {
  return window['go']['main']['App']['ListBranches'](arg1);
}

export function ListFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2, arg3);
}

export function ListManifests() {
  return window['go']['main']['App']['ListManifests']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function ReadTelemetryLog() {
  return window['go']['main']['App']['ReadTelemetryLog']();
}

export function RefreshConfig() {
  return window['go']['main']['App']['RefreshConfig']();
}

export function RepoAdd() {
  return window['go']['main']['App']['RepoAdd']();
}

export function RepoRemove() {
  return window['go']['main']['App']['RepoRemove']();
}

export function RunTelemetry(arg1) {
  return window['go']['main']['App']['RunTelemetry'](arg1);
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2);
}

export function SetOverride(arg1, arg2) {
  return window['go']['main']['App']['SetOverride'](arg1, arg2);
}

export function SkipUpdate(arg1) {
  return window['go']['main']['App']['SkipUpdate'](arg1);
}

export function Sync() {
  return window['go']['main']['App']['Sync']();
}

export function UninstallFile(arg1) {
  return window['go']['main']['App']['UninstallFile'](arg1);
}

export function Update() {
  return window['go']['main']['App']['Update']();
}
