// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {commands} from '../models';
import {model} from '../models';
import {main} from '../models';

export function DiffFile(arg1:string):Promise<commands.DiffResult>;

export function GetConfig(arg1:string):Promise<model.Config>;

export function GetState():Promise<commands.StateResult>;

export function InitWorkspace(arg1:string):Promise<void>;

export function InstallFile(arg1:string):Promise<commands.FileResult>;

export function ListBranches(arg1:string):Promise<Array<string>>;

export function ListFiles(arg1:string,arg2:string,arg3:string):Promise<commands.ListFilesResult>;

export function ListManifests():Promise<Array<model.Manifest>>;

export function ListWorkspaces():Promise<Array<main.WorkspaceInfo>>;

export function OpenFile(arg1:string):Promise<void>;

export function ReadTelemetryLog():Promise<Array<model.TelemetryEntry>>;

export function RefreshConfig():Promise<void>;

export function RepoAdd():Promise<commands.RepoAddResult>;

export function RepoRemove():Promise<void>;

export function RunTelemetry(arg1:string):Promise<commands.TelemetryRunResult>;

export function SelectWorkspace():Promise<commands.StateResult>;

export function SetConfig(arg1:string,arg2:model.Config):Promise<commands.SetConfigResult>;

export function SetOverride(arg1:string,arg2:string):Promise<commands.FileResult>;

export function SkipUpdate(arg1:string):Promise<commands.FileResult>;

export function Sync():Promise<commands.SyncResult>;

export function UninstallFile(arg1:string):Promise<commands.FileResult>;

export function Update():Promise<commands.UpdateResult>;
