// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToWorkspace() {
  return window['go']['main']['App']['AddToWorkspace']();
}

export function CLIFound() {
  return window['go']['main']['App']['CLIFound']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CloseWorkspace() {
  return window['go']['main']['App']['CloseWorkspace']();
}

export function DiffFile(arg1) {
  return window['go']['main']['App']['DiffFile'](arg1);
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function InitWorkspace(arg1) {
  return window['go']['main']['App']['InitWorkspace'](arg1);
}

export function InstallCLI() {
  return window['go']['main']['App']['InstallCLI']();
}

export function InstallFile(arg1) {
  return window['go']['main']['App']['InstallFile'](arg1);
}

export function ListBranches() {
  return window['go']['main']['App']['ListBranches']();
}

export function ListManifests() {
  return window['go']['main']['App']['ListManifests']();
}

export function ListPresets() {
  return window['go']['main']['App']['ListPresets']();
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function ReadTelemetryLog() {
  return window['go']['main']['App']['ReadTelemetryLog']();
}

export function RemoveFromWorkspace() {
  return window['go']['main']['App']['RemoveFromWorkspace']();
}

export function RestartDaemon() {
  return window['go']['main']['App']['RestartDaemon']();
}

export function RunTelemetry() {
  return window['go']['main']['App']['RunTelemetry']();
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}

export function SetOverride(arg1, arg2) {
  return window['go']['main']['App']['SetOverride'](arg1, arg2);
}

export function SetWorkspaceMenuVisible(arg1) {
  return window['go']['main']['App']['SetWorkspaceMenuVisible'](arg1);
}

export function SkipUpdate(arg1) {
  return window['go']['main']['App']['SkipUpdate'](arg1);
}

export function SyncManifests() {
  return window['go']['main']['App']['SyncManifests']();
}

export function UninstallFile(arg1) {
  return window['go']['main']['App']['UninstallFile'](arg1);
}

export function UpdateAll() {
  return window['go']['main']['App']['UpdateAll']();
}

export function UpdateCLI() {
  return window['go']['main']['App']['UpdateCLI']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
